sprites = {
    'chest': 21,
    'xp': 13,
    'potion': 825,
    'mob': 200,
    'emerald': 50,

    'blaze': 66,
    'ender_dragon': 50,
    'pigman': 50,
    'magma_cube': 29,
    'guardian': 28,
    'ghast': 17,
    'endermite': 50,
    'enderman': 50,
    'elder_guardian': 28,
    'spider': 1,
    'creeper': 1,
    'skeleton': 1,
    'slime': 1,
    'zombie': 1,
    'cave_spider': 1,
    'witch': 1,
    'wither_skeleton': 1,
    'wither': 1,
    'silver_fish': 14,
}